apiVersion: v2
name: retail-store
description: Complete Retail Store Application
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: ui
    version: "1.0.0"
    repository: "file://../ui"
  - name: catalog
    version: "1.0.0"
    repository: "file://../catalog"
  - name: cart
    version: "1.0.0"
    repository: "file://../cart"
  - name: orders
    version: "1.0.0"
    repository: "file://../orders"
  - name: checkout
    version: "1.0.0"
    repository: "file://../checkout"
